whisper:
  model_size: large-v3
  lang: russian
  is_translate: false
  beam_size: 12
  log_prob_threshold: -1.0
  no_speech_threshold: 0.5
  compute_type: float16
  best_of: 12
  patience: 2.0
  condition_on_previous_text: true
  prompt_reset_on_temperature: 0.3
  initial_prompt: 'Телефонное интервью по подбору персонала. Менеджер по персоналу
    Ольга из компании Данила Мастер проводит первичное интервью с кандидатом Екатериной.
    Разговор о вакансии менеджера фокус-продаж, требованиях к кандидату, опыте работы,
    зарплатных ожиданиях. Участники разговаривают вежливо, используют профессиональную
    терминологию. Ольга задает вопросы, Екатерина отвечает. Тема: поиск работы, собеседование,
    карьера.'
  temperature: 0.0
  compression_ratio_threshold: 2.8
  length_penalty: 1.2
  repetition_penalty: 1.01
  no_repeat_ngram_size: 3
  prefix: null
  suppress_blank: true
  suppress_tokens: '[-1]'
  max_initial_timestamp: 1.0
  word_timestamps: true
  prepend_punctuations: '"''"¿([{-'
  append_punctuations: '.,!?;:'
  max_new_tokens: null
  chunk_length: 30
  hallucination_silence_threshold: 1.0
  hotwords: Данила Мастер,Екатерина,Ольга,HeadHunter,компания,менеджер фокус-продажи,интервью,перезвоню,актуально,пожалуйста,здравствуйте,добрый
    день,спасибо,до свидания,в данный момент,в связи с тем,в том числе,в общем,работа,должность,зарплата,график,удаленно,офис,опыт,навыки,продажи,клиенты,руководитель,коллектив,мотивация,премьера,бонусы
  language_detection_threshold: 0.6
  language_detection_segments: 5
  batch_size: 16
  enable_offload: true
  add_timestamp: true
  file_format: SRT
vad:
  vad_filter: true
  threshold: 0.35
  min_speech_duration_ms: 250
  max_speech_duration_s: 12.0
  min_silence_duration_ms: 400
  speech_pad_ms: 200
diarization:
  is_diarize: true
  diarization_device: cuda
  enable_offload: true
bgm_separation:
  is_separate_bgm: false
  uvr_model_size: UVR-MDX-NET-Inst_HQ_4
  uvr_device: cuda
  segment_size: 256
  save_file: false
  enable_offload: true
translation:
  deepl:
    api_key: ''
    is_pro: false
    source_lang: Automatic Detection
    target_lang: English
  nllb:
    model_size: facebook/nllb-200-1.3B
    source_lang: null
    target_lang: null
    max_length: 200
  add_timestamp: false
