name: CI

on:
  workflow_dispatch:

  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - name: Install git and ffmpeg
        run: sudo apt-get update && sudo apt-get install -y git ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run test
        run: python -m pytest tests