name: Publish to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.2.3

jobs:
  build-and-push-webui:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract Git tag and short SHA
        id: vars
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui:${{ env.GIT_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui:${{ env.GIT_TAG }}-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui:latest

      - name: Log out of Docker Hub
        run: docker logout

  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract Git tag and short SHA
        id: vars
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui-backend:${{ env.GIT_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui-backend:${{ env.GIT_TAG }}-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/whisper-webui-backend:latest

      - name: Log out of Docker Hub
        run: docker logout
