name: Publish to GHCR

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - name: whisper-webui
            dockerfile: ./Dockerfile
          - name: whisper-webui-backend
            dockerfile: ./backend/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata
        id: meta
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "GIT_TAG=$TAG_NAME" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else
            echo "GIT_TAG=v1.0.0-$SHORT_SHA" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (version tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.component.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ matrix.component.name }}:${{ env.GIT_TAG }}

      - name: Tag and push as latest (if release)
        if: env.IS_RELEASE == 'true'
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER_LC }}/${{ matrix.component.name }}:${{ env.GIT_TAG }}
          docker tag ghcr.io/${{ env.REPO_OWNER_LC }}/${{ matrix.component.name }}:${{ env.GIT_TAG }} \
                     ghcr.io/${{ env.REPO_OWNER_LC }}/${{ matrix.component.name }}:latest
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/${{ matrix.component.name }}:latest
