name: Publish to Docker Hub

on:
  # Triggers minor version ( vX.Y.Z-ShortHash )
  push:
    branches:
      - master
  # Triggers major version ( vX.Y.Z )
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: [whisper-webui, whisper-webui-backend]

    steps:
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata
        id: meta
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          # Triggered by a release event — versioning as major ( vX.Y.Z )
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
            echo "GIT_TAG=$TAG_NAME" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          
          # Triggered by a general push event — versioning as minor ( vX.Y.Z-ShortHash )
          else
            git fetch --tags
            LATEST_TAG=$(git tag --list 'v*.*.*' | sort -V | tail -n1)
            FALLBACK_TAG="${LATEST_TAG:-v0.0.0}"
            echo "GIT_TAG=${FALLBACK_TAG}-${SHORT_SHA}" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Set Dockerfile path
        id: dockerfile
        run: |
          if [ "${{ matrix.name }}" = "whisper-webui" ]; then
            echo "DOCKERFILE=./Dockerfile" >> $GITHUB_ENV
          elif [ "${{ matrix.name }}" = "whisper-webui-backend" ]; then
            echo "DOCKERFILE=./backend/Dockerfile" >> $GITHUB_ENV
          else
            echo "Unknown component: ${{ matrix.name }}"
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (version tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.GIT_TAG }}

      - name: Tag and push as latest (if release)
        if: env.IS_RELEASE == 'true'
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.GIT_TAG }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:${{ env.GIT_TAG }} \
                     ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.name }}:latest

      - name: Log out of Docker Hub
        run: docker logout
