name: Shell Script Test

on:
  push:
    branches: ["feature/shell-script"]
    
env:
  PYTHON_VERSION: '3.9' 
  
jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Setup FFmpeg'
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
        architecture: 'arm64'
        linking-type: static

    - name: 'Execute Install.sh'
      run: |
        chmod +x ./Install.sh
        ./Install.sh

    - name: 'Execute start-webui.sh'
      run: |
        chmod +x ./start-webui.sh
        timeout 60s ./start-webui.sh || true

